# 06.1-异步编程-Promise 基础

## 一 异步编程与回调地狱

同步行为和异步行为的对立统一是计算机科学的一个基本概念。特别是在 JavaScript 这种单线程事件循环模型中，同步操作与异步操作更是代码所要依赖的核心机制。异步行为是为了优化因计算量大而时间长的操作，这样可以在等待其他操作完成的同时运行其他指令。

> 同步：对应内存中的顺序执行的指令，每条指令会严格按照出现顺序执行，程序执行的每一步都可以推断出程序执行的状态
> 异步：类似于系统中断，即当前进程外部的实体可以触发代码执行。如果代码要访问一些高延迟的资源，比如向远程服务器发送请求并等待响应，那么就会出现长时间的等待。

看一个基础的异步编程示例：

```js
function double(value) {
  setTimeout(() => {
    console.log(value)
  }, 1000)
}

// 先打印 last，再打印数值
double(3)
console.log('last')
```

异步行为虽然解决了高延迟资源访问时的等待问题，但是在实际开发中，会带来相当的不便，产生回调地狱的代码在可维护性上是相当差的：

```js
XHR.onreadystatechange = function(){
    if(){
        XHR2.onreadystatechange = function(){

            if(){

                XHR2.onreadystatechange = function(){

                    if(){
                        XHR2.onreadystatechange = function(){

                        }
                    }
                }
            }
        }
    }
}
```

异步的失败处理也同样不方便，因为要考虑成功回调、失败回调

```js
function double(value, success, failure) {
  setTimeout(() => {
    try {
      if (typeof value !== 'number') {
        throw 'Must provide number as first argument'
      }
      success(2 * value)
    } catch (e) {
      failure(e)
    }
  }, 1000)
}

const successCallback = (x) => console.log(`Success: ${x}`)
const failureCallback = (e) => console.log(`Failure: ${e}`)
double(3, successCallback, failureCallback) // Success: 6（大约 1000 毫秒之后）
double('b', successCallback, failureCallback) // Failure: Must provide number as first argument（大约 1000 毫秒之后）
```

异步的优化方案很多，包括将回调函数命名、全部采用函数名方式调用、优化代码结构、Node 中的第三方库 Async 等，但是这些在书写上都是治标不治本。

ECMAScript 提出了三个解决方案：

- Promise 方案：基本的异步解决方案
- generator 生成器方案：ES6 过渡方案
- async/await 方案：ES7 提出的方案，配合 Promise 能够完美解决 JS 异步问题

## 二 期约 Promise 对象

### 2.0 理解 Promise 对象

Promise 对象用来应对异步任务无法得知最终数据的问题。好比在我们在饭店里，点了一份饭。这份饭什么时候做好是未知的，但是服务员会给我们一份点餐凭证，我们可以依据该凭证在菜做好后拿到之前点的菜。

在等待做菜期间，我们可以去做其他的事情，比如聊天、刷手机等，尽管没有菜，但是在脑海里已经把手里的这个点餐凭单号作为菜的占位符了，这在本质上是一个未来的值。

当服务员喊：某某号菜单完成，我们就可以依据手里的凭据去取得菜品了。也就是：一旦需要的值准备好了，就可以用这份承诺（Promise）换取到需要的值。

回调函数的方式是在处理好业务后，拿到真实值去做一个事情：

```js
function(cb){
  // 业务 doSomething，做完拿到最终结果  res
  const res = ''

  // 业务完成
  cb(res)  // 执行回调
}
```

而 Promise 其实是一种视觉上的包装：

```js
Promise(() => {
  // 业务 doSomething，做完拿到最终结果  res
  const res = ''

  // 业务完成，通知完成
  resole(res) // 业务失败则 reject()
}).then((res) => {
  // 拿到res
})
```

### 2.1 期约 Promise 基本概念

Promise 是异步编程的一种解决方案，比起传统的回调函数，体验更好，功能强大。

期约 Promise 名字最早起源于 1976 年，描述了一种异步程序的执行机制。到了 2010 年，CommonJS 实现的 Promises/A 规范开始流行。ES6 对市面流行的第三方 Promise/A+ 规范提供了完善支持，即 Promise 引用类型。Promise 是现在异步编程的核心机制，得到了所有现代浏览器的支持。

Promise 类是一个实现了 Thenable 接口的对象，使用它可以获取异步操作的消息，简单来说，Promise 像一个容器，保存了未来才会结束的事件：

```js
// 构造函数必须传参，否则报错，一般该参数称为执行器 executor
// 传入的函数用来修改 Promise 的执行结果，正确与错误的结果分别位于 resolve、reject 中
let p = new Promise((resolve, reject) => {
  setTimeout(() => {
    // 模拟 ajax
    let err = null
    let data = { uid: 1001 }
    if (err) {
      reject('发生了错误：', null)
    }
    resolve(data)
  })
})

// 实例方法 then：用于处理状态改变后的业务
p.then(
  (data) => {
    console.log(data) // 输出结果：{ uid: 1001 }
  },
  (err) => {
    console.log(err)
  }
)
```

从上看出，**期约的作用其实是抽象的表示了一个异步操作**。

### 2.2 实例方法 then()

Promise.prototype.then()方法接收两个可选的参数： onResolved 处理程序和 onRejected 处理程序，如果提供的话，则会在期约分别进入“兑现”和“拒绝”状态时执行：

```js
function onResolved(id) {
  setTimeout(console.log, 0, id, 'resolved')
}

function onRejected(id) {
  setTimeout(console.log, 0, id, 'rejected')
}

let p1 = new Promise((resolve, reject) => setTimeout(resolve, 3000))
let p2 = new Promise((resolve, reject) => setTimeout(reject, 3000))

p1.then(
  () => onResolved('p1'),
  () => onRejected('p1')
)

p2.then(
  () => onResolved('p2'),
  () => onRejected('p2')
)

//（ 3 秒后）
// p1 resolved
// p2 rejected
```

传给 then()的任何非函数类型的参数都会被静默忽略。如果想只提供 onRejected 参数，那就要在 onResolved 参数的位置上传入 undefined。这
样有助于避免在内存中创建多余的对象，对期待函数参数的类型系统也是一个交代。

### 2.3 实例方法 catch()

Promise.prototype.catch()方法用于给期约添加拒绝处理程序。这个方法只接收一个参数：onRejected 处理程序。事实上，这个方法就是一个语法糖，调用它就相当于调用 Promise.prototype.then(null, onRejected)。

```js
let p = Promise.reject()
let onRejected = function (e) {
  setTimeout(console.log, 0, 'rejected')
}
// 这两种添加拒绝处理程序的方式是一样的：
p.then(null, onRejected) // rejected
p.catch(onRejected) // rejected
```

Promise.prototype.catch()返回一个新的期约实例：

```js
let p1 = new Promise(() => {})
let p2 = p1.catch()
setTimeout(console.log, 0, p1) // Promise <pending>
setTimeout(console.log, 0, p2) // Promise <pending>
setTimeout(console.log, 0, p1 === p2) // false
```

then() 方法返回的仍然是一个 Promise 实例，所以可以使用 then 方法进行链式调用：

```js
let flag = false

// 在该函数内执行异步操作，并修改结果的状态值。
let p = new Promise(function (resolve, reject) {
  if (flag) {
    resolve('true...')
  } else {
    reject('false...')
  }
})

p.then((data) => {
  console.log('处理成功，结果为：', data)
}).catch((err) => {
  // 实例方法 catch：用于捕获错误
  console.log('处理失败，错误为：', err)
})
```

### 2.4 finally() 方法

Promise.prototype.finally()方法用于给期约添加 onFinally 处理程序，这个处理程序在期约转换为解决或拒绝状态时都会执行。这个方法可以避免 onResolved 和 onRejected 处理程序中出现冗余代码。但 onFinally 处理程序没有办法知道期约的状态是解决还是拒绝，所以这个方法主要用于添加清理代码。

```js
let p1 = Promise.resolve()
let p2 = Promise.reject()
let onFinally = function () {
  setTimeout(console.log, 0, 'Finally!')
}
p1.finally(onFinally) // Finally
p2.finally(onFinally) // Finally
```

Promise.prototype.finally()方法返回一个新的期约实例：

```js
let p1 = new Promise(() => {})
let p2 = p1.finally()
setTimeout(console.log, 0, p1) // Promise <pending>
setTimeout(console.log, 0, p2) // Promise <pending>
setTimeout(console.log, 0, p1 === p2) // false
```

这个新期约实例不同于 then()或 catch()方式返回的实例。因为 onFinally 被设计为一个状态无关的方法， 所以在大多数情况下它将表现为父期约的传递。对于已解决状态和被拒绝状态都是如此。

```js
let p1 = Promise.resolve('foo')

let p2 = p1.finally()
let p3 = p1.finally(() => undefined)
let p4 = p1.finally(() => {})
let p5 = p1.finally(() => Promise.resolve())
let p6 = p1.finally(() => 'bar')
let p7 = p1.finally(() => Promise.resolve('bar'))
let p8 = p1.finally(() => Error('qux'))
setTimeout(console.log, 0, p2) // Promise <resolved>: foo
setTimeout(console.log, 0, p3) // Promise <resolved>: foo
setTimeout(console.log, 0, p4) // Promise <resolved>: foo
setTimeout(console.log, 0, p5) // Promise <resolved>: foo
setTimeout(console.log, 0, p6) // Promise <resolved>: foo
setTimeout(console.log, 0, p7) // Promise <resolved>: foo
setTimeout(console.log, 0, p8) // Promise <resolved>: foo
```

如果返回的是一个待定的期约，或者 onFinally 处理程序抛出了错误（显式抛出或返回了一个拒绝期约），则会返回相应的期约（待定或拒绝），如下所示：

```js
// Promise.resolve()保留返回的期约
let p9 = p1.finally(() => new Promise(() => {}))
let p10 = p1.finally(() => Promise.reject())
// Uncaught (in promise): undefined
setTimeout(console.log, 0, p9) // Promise <pending>
setTimeout(console.log, 0, p10) // Promise <rejected>: undefined
let p11 = p1.finally(() => {
  throw 'baz'
})
// Uncaught (in promise) baz
setTimeout(console.log, 0, p11) // Promise <rejected>: baz]
```

返回待定期约的情形并不常见，这是因为只要期约一解决，新期约仍然会原样后传初始的期约：

```js
let p1 = Promise.resolve('foo')
// 忽略解决的值
let p2 = p1.finally(
  () => new Promise((resolve, reject) => setTimeout(() => resolve('bar'), 100))
)
setTimeout(console.log, 0, p2) // Promise <pending>
setTimeout(() => setTimeout(console.log, 0, p2), 200)
// 200 毫秒后：
// Promise <resolved>: foo
```

## 三 期约 Promise 状态

### 3.1 期约状态机

直接把一个期约实例传递打印出来时控制台输出表示该实例处于待定（pending）状态：

```js
let p = new Promise(() => {})
console.log(p) // Promise <pending>)
```

这说明期约是一个有状态的对象，可能处于如下 3 种状态之一：

- 待定（pending）：表示尚未开始或者正在执行中
- 兑现（fulfilled）：表示已经成功完成，有时也称为解决（resolved）
- 拒绝（rejected）：表示没有成功完成

期约的状态代表期约是否完成，这些状态只能由异步操作改变。待定（ pending）是期约的最初始状态。在待定状态下，期约可以落定（ settled）为代表成功的兑现（ fulfilled）状态，或者代表失败的拒绝（ rejected）状态。无论落定为哪种状态都是不可逆的，但是转换为兑现或拒绝并不能保证期约必然会脱离待定状态。

－旦状态改变就不会再变，任何时候都可以得到这个结果。 Promise 对象的状态改变只有两种可能：

- 从 Pending 变为 Fulfilled，由构造函数的参数 resolve 函数决定
- 从 Pending 变为 Rejected，由构造函数的参数 reject 函数决定

只要这两种情况发生，状态就会固定，不会再变，而是一直保持这个结果，这时就称为 Resolved （己定型） 。 就算改变己经发生，再对 Promise 对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同。事件的特点是，如果错过了它，再去监听是得不到结果的 。

### 3.2 执行器函数

**期约的状态是私有的，不能直接通过 JavaScript 检测到，而且期约的状态也不能被外部 JavaScript 代码修改**，这样做才能有效隔离外部的同步代码。也因此只能在期约的执行器函数中完成状态改变。执行器函数主要有两项职责：初始化期约的异步行为和控制状态的最终转换。其中，控制期约状态的转换是
通过调用它的两个函数参数实现的。这两个函数参数通常都命名为 resolve()和 reject()。调用 resolve()会把状态切换为兑现，调用 reject()会把状态切换为拒绝。另外，调用 reject()也会抛出错误。

状态转换为解决：

```js
let p = new Promise((resolve, reject) => {
  resolve()
})
setTimeout(console.log, 0, p) // Promise {<fulfilled>: undefined}
```

状态转换为拒绝：

```js
let p = new Promise((resolve, reject) => {
  reject()
})
setTimeout(console.log, 0, p) // 报错Promise {<rejected>: undefined}
```

无论 resolve()和 reject()中的哪个被调用，状态转换都不可撤销了。于是继续修改状态会静默失败，如下所示：

```js
let p = new Promise((resolve, reject) => {
  resolve()
  reject() // 没有效果
})
setTimeout(console.log, 0, p) // Promise <resolved>
```

为避免期约卡在待定状态，可以添加一个定时退出功能。比如，可以通过 setTimeout 设置一个 10 秒钟后无论如何都会拒绝期约的回调：

```js
let p = new Promise((resolve, reject) => {
  setTimeout(reject, 10000) // 10 秒后调用 reject()
  // 执行函数的逻辑
})
setTimeout(console.log, 0, p) // Promise <pending>
setTimeout(console.log, 11000, p) // 11 秒后再检查状态
// (After 10 seconds) Uncaught error
// (After 11 seconds) Promise <rejected>
```

因为期约的状态只能改变一次，所以这里的超时拒绝逻辑中可以放心地设置让期约处于待定状态的最长时间。如果执行器中的代码在超时之前已经解决或拒绝，那么超时回调再尝试拒绝也会静默失败。

### 3.3 同步/异步执行的二元性

```js
try {
  throw new Error('foo')
} catch (e) {
  console.log(e) // Error: foo
}

// Uncaught (in promise) Error: bar
try {
  Promise.reject(new Error('bar'))
} catch (e) {
  console.log(e)
}
```

第一个 try/catch 抛出并捕获了错误，第二个 try/catch 抛出错误却没有捕获到，因为后者没有通过异步模式捕获错误。从这里可以看出期约真正的异步特性：它们是同步对象（在同步执行模式中使用），但也是异步执行模式的媒介。

代码一旦开始以异步模式执行，则唯一与之交互的方式就是使用异步结构——更具体地说，就是期约的方法。

### 3.4 Promsie 状态缺点

Promise 也有一些缺点：

- 无法取消 Promise，一旦新建它就会立即执行，无法中途取消。
- 如果不设置回调函数，Promise 内部抛出的错误不会反应到外部。
- 当处于 Pending 状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

如果某些事件不断地反复发生， 一般来说，使用 Stream 模式 （nodejs.org/api/strearm.html）是比使用 Promise 更好的选择。
