# 06.2-异步编程-Promise 静态方法

## 一 Promise 静态方法

### 1.1 Promise.resolve()

除了执行器函数可以转换为落定状态，通过调用 Promise.resolve() 静态方法，也可以实例化一个解决的期约：

```js
// 二者没有区别
let p1 = new Promise((resolve, reject) => resolve())
let p2 = Promise.resolve()
```

这个解决的期约的值对应着传给 Promise.resolve()的第一个参数。使用这个静态方法，实际上可以把任何值都转换为一个期约：

```js
setTimeout(console.log, 0, Promise.resolve()) // Promise <resolved>: undefined
setTimeout(console.log, 0, Promise.resolve(3)) // Promise <resolved>: 3

// 多余的参数会忽略
setTimeout(console.log, 0, Promise.resolve(4, 5, 6)) // Promise <resolved>: 4
```

如果传入的参数本身是一个期约，那它的行为就类似于一个空包装。因此，Promise.resolve() 可以说是一个幂等方法，如下所示：

```js
let p = Promise.resolve(7)
setTimeout(console.log, 0, p === Promise.resolve(p)) // true

setTimeout(console.log, 0, p === Promise.resolve(Promise.resolve(p))) // true
```

这个幂等性会保留传入期约的状态：

```js
let p = new Promise(() => {})
setTimeout(console.log, 0, p) // Promise <pending>
setTimeout(console.log, 0, Promise.resolve(p)) // Promise <pending>
setTimeout(console.log, 0, p === Promise.resolve(p)) // true
```

这个静态方法能够包装任何非期约值，包括错误对象，并将其转换为解决的期约。因此，也可能导致不符合预期的行为：

```js
let p = Promise.resolve(new Error('foo'))
setTimeout(console.log, 0, p) // Promise <resolved>: Error: foo
```

### 1.2 Promise.reject()

Promise.reject() 会实例化一个拒绝的期约并抛出一个异步错误（这个错误不能通过 try/catch 捕获，而只能通过拒绝处理程序捕获）。下面的两个期约实例实际上是一样的：

```js
let p1 = new Promise((resolve, reject) => reject())
let p2 = Promise.reject()
```

这个拒绝的期约的理由就是传给 Promise.reject() 的第一个参数。这个参数也会传给后续的拒绝处理程序：

```js
let p = Promise.reject(3)
setTimeout(console.log, 0, p) // Promise <rejected>: 3
p.then(null, (e) => setTimeout(console.log, 0, e)) // 3
```

注意：Promise.reject() 并没有照搬 Promise.resolve() 的幂等逻辑。如果给它传一个期约对象，则这个期约会成为它返回的拒绝期约的理由：

```js
// Promise <rejected>: Promise <resolved>
setTimeout(console.log, 0, Promise.reject(Promise.resolve()))
```

### 1.3 Promise.all()

Promise 类提供两个将多个期约实例组合成一个期约的静态方法： Promise.all()和 Promise.race()。而合成后期约的行为取决于内部期约的行为。

Promise.all()静态方法创建的期约会在一组期约全部解决之后再解决。这个静态方法接收一个可迭代对象，返回一个新期约：

```js
let p1 = Promise.all([Promise.resolve(), Promise.resolve()])
// 可迭代对象中的元素会通过 Promise.resolve()转换为期约
let p2 = Promise.all([3, 4])
// 空的可迭代对象等价于 Promise.resolve()
let p3 = Promise.all([])
// 无效的语法
let p4 = Promise.all()
// TypeError: cannot read Symbol.iterator of undefined
```

合成的期约只会在每个包含的期约都解决之后才解决：

```js
let p = Promise.all([
  Promise.resolve(),
  new Promise((resolve, reject) => setTimeout(resolve, 1000)),
])
setTimeout(console.log, 0, p) // Promise <pending>
p.then(() => setTimeout(console.log, 0, 'all() resolved!'))
// all() resolved!（大约 1 秒后）
```

如果至少有一个包含的期约待定，则合成的期约也会待定。如果有一个包含的期约拒绝，则合成的期约也会拒绝：

```js
// 永远待定
let p1 = Promise.all([new Promise(() => {})])
setTimeout(console.log, 0, p1) // Promise <pending>
// 一次拒绝会导致最终期约拒绝
let p2 = Promise.all([Promise.resolve(), Promise.reject(), Promise.resolve()])
setTimeout(console.log, 0, p2) // Promise <rejected>
// Uncaught (in promise) undefined
```

如果所有期约都成功解决，则合成期约的解决值就是所有包含期约解决值的数组，按照迭代器顺序：

```js
let p = Promise.all([Promise.resolve(3), Promise.resolve(), Promise.resolve(4)])
p.then((values) => setTimeout(console.log, 0, values)) // [3, undefined, 4]
```

如果有期约拒绝，则第一个拒绝的期约会将自己的理由作为合成期约的拒绝理由。之后再拒绝的期约不会影响最终期约的拒绝理由。不过，这并不影响所有包含期约正常的拒绝操作。合成的期约会静默处理所有包含期约的拒绝操作，如下所示：

```js
// 虽然只有第一个期约的拒绝理由会进入
// 拒绝处理程序，第二个期约的拒绝也
// 会被静默处理，不会有错误跑掉
let p = Promise.all([
  Promise.reject(3),
  new Promise((resolve, reject) => setTimeout(reject, 1000)),
])
p.catch((reason) => setTimeout(console.log, 0, reason)) // 3
// 没有未处理的错误
```

### 1.4 Promise.race()

Promise.race()静态方法返回一个包装期约，是一组集合中最先解决或拒绝的期约的镜像。这个方法接收一个可迭代对象，返回一个新期约：

```js
let p1 = Promise.race([Promise.resolve(), Promise.resolve()])
// 可迭代对象中的元素会通过 Promise.resolve()转换为期约
let p2 = Promise.race([3, 4])
// 空的可迭代对象等价于 new Promise(() => {})
let p3 = Promise.race([])
// 无效的语法
let p4 = Promise.race()
// TypeError: cannot read Symbol.iterator of undefined
```

Promise.race()不会对解决或拒绝的期约区别对待。无论是解决还是拒绝，只要是第一个落定的期约， Promise.race()就会包装其解决值或拒绝理由并返回新期约：

```js
// 解决先发生，超时后的拒绝被忽略
let p1 = Promise.race([
  Promise.resolve(3),
  new Promise((resolve, reject) => setTimeout(reject, 1000)),
])
setTimeout(console.log, 0, p1) // Promise <resolved>: 3
// 拒绝先发生，超时后的解决被忽略
let p2 = Promise.race([
  Promise.reject(4),
  new Promise((resolve, reject) => setTimeout(resolve, 1000)),
])
setTimeout(console.log, 0, p2) // Promise <rejected>: 4
// 迭代顺序决定了落定顺序
let p3 = Promise.race([
  Promise.resolve(5),
  Promise.resolve(6),
  Promise.resolve(7),
])
setTimeout(console.log, 0, p3) // Promise <resolved>: 5
```

如果有一个期约拒绝，只要它是第一个落定的，就会成为拒绝合成期约的理由。之后再拒绝的期约不会影响最终期约的拒绝理由。不过，这并不影响所有包含期约正常的拒绝操作。与 Promise.all()类似，合成的期约会静默处理所有包含期约的拒绝操作，如下所示：

```js
// 虽然只有第一个期约的拒绝理由会进入
// 拒绝处理程序，第二个期约的拒绝也
// 会被静默处理，不会有错误跑掉
let p = Promise.race([
  Promise.reject(3),
  new Promise((resolve, reject) => setTimeout(reject, 1000)),
])
p.catch((reason) => setTimeout(console.log, 0, reason)) // 3
// 没有未处理的错误
```
